language:
  - cpp
compiler:
  - g++-6
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-6
      - g++-6
      - libboost-python-dev
      - libpython2.7-dev
install:
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp
before_script:  
  - export PATH=$PATH:$PWD/.tmp
  - mkdir build
  - cd build
  - cmake --version && g++-6 --version
  - cmake -GNinja ..
script:
  - ninja -v
